-- Database / schemas
CREATE DATABASE IF NOT EXISTS RT_INTEL;
CREATE SCHEMA IF NOT EXISTS RT_INTEL.RAW;
CREATE SCHEMA IF NOT EXISTS RT_INTEL.CURATED;
CREATE SCHEMA IF NOT EXISTS RT_INTEL.ANALYTICS;

-- RAW tables (loaded by Kafka Connector)
CREATE TABLE IF NOT EXISTS RT_INTEL.RAW.ORDERS_EVENTS (
  RECORD_METADATA VARIANT,
  RECORD_CONTENT  VARIANT,
  LOAD_TIME       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RT_INTEL.RAW.PAYMENTS_EVENTS (
  RECORD_METADATA VARIANT,
  RECORD_CONTENT  VARIANT,
  LOAD_TIME       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Helpful views to see payload quickly
CREATE OR REPLACE VIEW RT_INTEL.RAW.V_ORDERS AS
SELECT
  LOAD_TIME,
  RECORD_CONTENT:order_id::STRING AS order_id,
  RECORD_CONTENT:customer_id::STRING AS customer_id,
  RECORD_CONTENT:amount::FLOAT AS amount,
  RECORD_CONTENT:currency::STRING AS currency,
  RECORD_CONTENT:event_ts::TIMESTAMP_NTZ AS event_ts,
  RECORD_CONTENT AS payload
FROM RT_INTEL.RAW.ORDERS_EVENTS;

CREATE OR REPLACE VIEW RT_INTEL.RAW.V_PAYMENTS AS
SELECT
  LOAD_TIME,
  RECORD_CONTENT:payment_id::STRING AS payment_id,
  RECORD_CONTENT:order_id::STRING AS order_id,
  RECORD_CONTENT:status::STRING AS status,
  RECORD_CONTENT:amount::FLOAT AS amount,
  RECORD_CONTENT:event_ts::TIMESTAMP_NTZ AS event_ts,
  RECORD_CONTENT AS payload
FROM RT_INTEL.RAW.PAYMENTS_EVENTS;
